name: Test GitHub Workflows

on:
  push:
    branches:
      - "**"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-jsp-env:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set PYTHONIOENCODING to UTF-8
        run: |
          echo "PYTHONIOENCODING=UTF-8" >> $GITHUB_ENV

      - name: Test 
        run: |
          python -c "print('\33[31m ███▌         ▟███▛▟███████▛▐███▌           ┃       ▐█▀▜▙█▙   ███████▐█ ▐█')"
